DB_NAME = "snake_db"
DB_USER = "torekhan.danial"
DB_PASSWORD = ""
DB_HOST = "localhost"
DB_PORT = "5432"

WIDTH = 800
HEIGHT = 700
CELL_SIZE = 20

GAME_TOP = 80
GRID_WIDTH = WIDTH // CELL_SIZE
GRID_HEIGHT = (HEIGHT - GAME_TOP) // CELL_SIZE